### ISSUE TITLE
Awesome theme, with a small alignment issue between title and subtitle when logo is added :)

### ISSUE THREAD

**Issue by MaskyS** [zutrinken/kava#1]
Always loved your work with Ghost themes, @zutrinken :smile: Was testing this one out and found what appears to be a minor bug. When a publication logo is added, the there's a misalignment between the title and subtitle. Example: https://screenshots.firefox.com/anoliB30DImDkMI1/localhost

**Comment by zutrinken** [comment]
Hey @MaskyS ... thanks a lot! Unfortunately that was by design 🙈. The author archive has the same pattern with the avatar in front. I'll keep it in mind if I update the layout sometime. Have a nice day!
